version: "3"

services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    volumes:
      - ./:/app
    depends_on:
      - server-database
    environment:
      - DATABASE_URL=server-database
      - PORT=8081
  server-database:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
